# Generated by Django 4.2.2 on 2023-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nota_c1', models.FloatField()),
                ('nota_c2', models.FloatField()),
                ('nota_c3', models.FloatField()),
                ('clasificacion', models.CharField(choices=[('Milagro', 'Milagro'), ('Difil', 'Difil'), ('Aceptable', 'Aceptable'), ('Bien', 'Bien'), ('Excelente', 'Excelente')], max_length=10)),
            ],
        ),
    ]
