# Generated by Django 4.2.2 on 2023-06-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
