# Generated by Django 4.2.2 on 2023-06-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_note', '0002_alter_validacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='clasificacion',
            field=models.CharField(choices=[('Milagro', 'Milagro'), ('Difil', 'Difil'), ('Aceptable', 'Aceptable'), ('Bien', 'Bien'), ('Excelente', 'Excelente'), ('Perdido', 'Perdido')], max_length=10),
        ),
    ]
