# Generated by Django 4.2.2 on 2023-06-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_note', '0003_alter_validacion_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('clasificacion', models.CharField(choices=[('Milagro', 'Milagro'), ('Difil', 'Difil'), ('Aceptable', 'Aceptable'), ('Bien', 'Bien'), ('Excelente', 'Excelente'), ('Perdido', 'Perdido')], max_length=10)),
            ],
        ),
    ]
