# Generated by Django 4.2.2 on 2023-06-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_note', '0004_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='clasificacion',
            field=models.CharField(choices=[('Milagro', 'Milagro'), ('Difícil', 'Difícil'), ('Aceptable', 'Aceptable'), ('Bien', 'Bien'), ('Excelente', 'Excelente'), ('Perdido', 'Perdido')], max_length=10),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='clasificacion',
            field=models.CharField(choices=[('Milagro', 'Milagro'), ('Difícil', 'Difícil'), ('Aceptable', 'Aceptable'), ('Bien', 'Bien'), ('Excelente', 'Excelente'), ('Perdido', 'Perdido')], max_length=10),
        ),
    ]
